version: '3.8'

services:
  backend:
    image: backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.production
    ports:
      - 80:3000
    networks:
      - online-class
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongoDB
    ports:
      - 27018:27017
    volumes:
      - mongoDB:/data/db
    networks:
      - online-class
    restart: always

networks:
  online-class:
    driver: bridge

volumes:
  mongoDB: